name: ml-workshop-advanced
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.7
  - scikit-learn=1.0.*
  - seaborn=0.11.2
  - pandas
  - jupyterlab=3.1.*
  - imbalanced-learn=0.8.*
